-- local format_on_save_filetypes = {
--   'javascript',
--   'typescript',
--   '*.js',
--   '*.ts',
-- }

-- local formatter = require('formatter')

-- local function prettier()
--   return {
--     exe = 'prettier',
--     args = {
--       '--config-precedence',
--       'prefer-file',
--       '--no-bracket-spacing',
--       '--single-quote',
--       '--trailing-comma',
--       'es5',
--       '--arrow-parens',
--       'avoid',
--       '--stdin-filepath',
--       vim.fn.shellescape(vim.api.nvim_buf_get_name(0)),
--     },
--     stdin = true,
--   }
-- end

-- local function prettierd()
--   return {
--     exe = "prettierd",
--     args = {
--       vim.fn.shellescape(vim.api.nvim_buf_get_name(0)),
--     },
--     stdin = true,
--   }
-- end

-- formatter.setup {
--   filetype = {
--     typescript = { prettierd },
--     javascript = { prettierd },
--   }
-- }

-- local fmt_group = vim.api.nvim_create_augroup('FmtOnSave', { clear = true })
-- vim.api.nvim_create_autocmd('BufWritePre', {
--   group = fmt_group,
--   pattern = format_on_save_filetypes,
--   callback = function()
--     vim.cmd.FormatWrite()
--   end
-- })
