#! /bin/bash

bucketName='red-panda'
url='https://i.red-panda.red/'

temp=$(mktemp /tmp/XXXXXX.png)
cat /dev/stdin > $temp

[[ -s $temp ]] || exit 1;

a=$(b2 upload_file $bucketName $temp $(sed 's,/tmp/,,' <<< $temp) --noProgress)

json=$(echo $a | grep -o '\{.*\}$')
filename=$(echo $json | jq -r '.fileName')

[[ -z $filename ]] && { notify-send -u critical 'Screenshot Upload Error' 'The server returned null or did not respond in time' ; exit 1 ; }

fullurl="$url$filename"

echo $fullurl >> ~/Pictures/screenshots.txt
echo -n $fullurl
echo -n $fullurl | xclip -sel clip
notify-send -u normal -i $temp 'Screenshot Uploaded' $fullurl

rm $temp

# vim:ft=sh
