#!/bin/sh

bspc config focus_follows_pointer true

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           0
bspc config single_monocle       true

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config top_padding           27

bspc config normal_border_color '#2E3440'
bspc config active_border_color '#2E3440'
bspc config focused_border_color '#81a1c1'

bspc config presel_feedback_color '#bf616a'

# rules
bspc rule -a "Picture in picture" state=floating
