#!/usr/bin/env bash

#
# REQUIREMENTS:
# jq
# b2 command line thing
# xclip
# notify-send
#

. ~/scripts/util

bucketName='red-panda'
url='https://i.red-panda.red/'

adjectives="$HOME/scripts/adjectives.txt"
animals="$HOME/scripts/animals.txt"

# bucketName='porg-imgs'
# url='https://i.what-the-f.uk/'

temp=$(mktemp /tmp/XXXXXX.png)
cat /dev/stdin > $temp

[[ -s $temp ]] || exit 1;

cat $temp | xclip -sel clip -t image/png

ext=$(rg '\.(.*)$' -o -r '$1'<<< $(basename "$temp"))

adjective=$(capitalize_first_word $(shuf -n 1 "$adjectives"))
animal=$(capitalize_first_word $(shuf -n 1 "$animals"))

file="${adjective}${animal}.${ext}"

a=$(b2 upload_file $bucketName $temp "$file" --noProgress)
# a=$(b2 upload_file $bucketName $temp $(sed 's,/tmp/,,' <<< $temp) --noProgress)

json=$(echo $a | grep -o '\{.*\}$')
filename=$(echo $json | jq -r '.fileName')

if [[ -z $filename ]]; then
  notify-send -u critical 'Screenshot Upload Error' 'The server returned null or did not respond in time'
  exit 1
fi

fullurl="$url$filename"
# fullurl="$url$"

echo $fullurl >> ~/Pictures/screenshots.txt
printf '%s' $fullurl
# echo -n $fullurl | xclip -sel clip
# xclip -sel clip <<< $fullurl
printf '%s' $fullurl | xclip -sel clip
notify-send -u normal -i $temp 'Screenshot Uploaded' $fullurl

rm $temp

# vim:ft=sh
