#!/usr/bin/env bash

# A wrapper around curl for making requests to Discord. Defaults to application/json for requests with payloads
#
# USAGE:
#   curlbot /gateway/bot
#   curlbot /channels/:channel/messages -d '{"content":"Hello, world!"}'
#
# REQUIREMENTS:
#   - curl
#   - Bash 4.4 or later
#
# NOTE FOR MAC USERS:
#   You MUST install Bash yourself. MacOS comes with Bash 3.
#     - Homebrew: `brew install bash`
curlbot() {
  : ${DISCORD_API_URL:="https://discord.com/api"}
  : ${DISCORD_API_VERSION:="10"}
  : ${USE_AUTH:=1}
  : ${AUTH_HEADER:="Bot $DISCORD_TOKEN"}

  DEFAULT_CONTENT_TYPE="application/json"

  path=""

  takesData=0
  hasContentTypeHeader=0
  hasAuthHeader=0

  for arg; do
    shift

    if [[ ! -z "$path "&& "$arg" =~ ^/.*$ ]]; then
      path="$arg"
      continue
    fi

    if [[ "$takesData" == 0 && "$arg" =~ ^-(d|-data(-(binary|urlencode|raw))?|F|-form)$ ]]; then
      takesData=1
    fi

    shopt -s nocasematch
    if [[ "$hasContentTypeHeader" == 0 && "$arg" =~ ^content-type:[[:space:]](.*)$ ]]; then
      hasContentTypeHeader=1
    fi

    if [[ "$hasAuthHeader" == 0 && "$arg" =~ ^authorization:.*$ ]]; then
      hasAuthHeader=1
    fi
    shopt -u nocasematch

    set -- "$@" "$arg"
  done

  curlArgs=(
    "-s"
    "-S"
    "--url"
    "${DISCORD_API_URL}/v${DISCORD_API_VERSION}${path}"
    "${@}"
  )

  if [[ "$takesData" == 1 && "$hasContentTypeHeader" == 0 ]]; then
    curlArgs+=(
      "-H"
      "Content-Type: ${DEFAULT_CONTENT_TYPE}"
    )
  fi

  if [[ "$USE_AUTH" == 1 && "$hasAuthHeader" == 0 && ! -z "$DISCORD_TOKEN" ]]; then
    curlArgs+=(
      "-H"
      "Authorization: ${AUTH_HEADER}"
    )
  fi

  eval "curl ${curlArgs[@]@Q}"
}

curlbot "$@"
