#!/usr/bin/env bash
echo Updating mirrorlist &&
reflector --sort rate --protocol https --fastest 50 --number 100 --save /etc/pacman.d/mirrorlist &&
echo Refreshing mirrorlist &&
pacman -Syy &&
echo Refresh complete.
