live_config_reload = true

import = [
  "~/.config/alacritty/ayu.toml",
]

[shell]
program = "/opt/homebrew/bin/tmux"
args = ["new", "-A"]

[window]
startup_mode = "Maximized"
option_as_alt = "OnlyLeft"
decorations = "Buttonless"

[font]
# to fix weird font antialiasing issues:
# defaults write org.alacritty AppleFontSmoothing -int 0

size = 12
normal = {family = "BerkeleyMono Nerd Font", style = "Regular"}
bold = {family = "BerkeleyMono Nerd Font", style = "Bold"}
italic = {family = "BerkeleyMono Nerd Font", style = "Italic"}
bold_italic = {family = "BerkeleyMono Nerd Font", style = "Bold Italic"}

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BOH"
key = "Left"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BOF"
key = "Right"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B\u007F"
key = "Back"
mods = "Alt"
